name: Post Job to Twitter

on:
  schedule:
    - cron: "30 12 * * *"  # Runs at 7:30 AM EST (12:30 UTC)
  workflow_dispatch:  # Allows manual execution

jobs:
  tweet-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install tweepy

      - name: Post Latest Job to Twitter
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python post_to_twitter.py

      - name: Save Logs
        run: cat twitter_post.log
